DocConnect v1 FrontEnd PR
adarachel/doctors-appointment-frontend pull request #16
Opened 2023-10-11 12:38 UTC by ankitt26

> Link to 🎋 Doctors-Appoinments-Front-End [click here](https://github.com/Enning94/Doctors_Appointment_Backend/)

### Hello Code Reviewer, Hope you're doing good 👋🏿
In this Project we did-

Project Requirements:
- [ ] User Authentication: Implement proper user authentication for the website, ensuring that only authenticated users can access certain features. This is a requirement if your group consists of five people.

Navigation Panel:
- [ ] User Login: Allow users to log in to the website by entering their username or email and password. Ensure proper authentication.
- [ ] Links: Display links in the navigation panel to the following sections:
  - [ ] Motorcycles/Doctors/Classes/Items: These sections should align with the chosen theme.
  - [ ] "Reserve" Form: Users should have the option to make reservations.
  - [ ] "My Reservations": Display a list of reservations made by the user.
  - [ ] "Add Motorcycle/Doctor/Class/Item": This link is visible to all users.
  - [ ] "Delete Motorcycle/Doctor/Class/Item": This link is visible to all users.

Main Page:
- [ ] Display a list of items related to the chosen theme. The list should be visible on the main page.

Item Details:
- [ ] When a user selects a specific item, show a details page with its full description (excluding the "Rotate image" button).

Reservations:
- [ ] In the details page, include a "Reserve" button for users to make reservations.

Additional Features (Required for teams with 3-4 & 5 members, optional for others):
- [ ] "Add Item" Form: When the user clicks the "Add Item" link, provide a form for adding a new item.
- [ ] Responsiveness: Make the application responsive, creating both mobile and desktop versions.

Deleting Items:
- [ ] When the user clicks the "Delete Item" link, show a list of all items with title and a "Delete" button.
- [ ] Mark Items as Removed: When the user clicks the "Delete" button, the selected item should be marked as removed and not displayed in the main list anymore.

Booking:
- [ ] To reserve an appointment, the user has to select a date and city. The username and selected item should be autofilled.
- [ ] Use the design based on "Book a Vespa Test-Ride" and include all necessary inputs.
- [ ] Users can also access the "Reserve" page from the navigation panel, with only the username autofilled.

My Reservations:
- [ ] When the user clicks the "My Reservations" link in the navigation panel, they can see a list of their reservations, including information about the item name, date, and city.

Documentation:
- [ ] Add full documentation for your API.

Additional Features (Required only for teams with 5 members, optional for others):
- [ ] Proper User Authentication: Implement proper user authentication from the front-end to the server.
- [ ] Restricted Access: Ensure that the "Add Item" and "Delete Item" links are accessible only by users who are administrators.

2023-10-11 16:01 UTC, Meltrust requested changes
Hi @ankitt26,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-11 16:01 UTC, Meltrust commented on src/App.js
> +const App = () => (
- [ ] When I go to "create doctor", I do so, and then (since I'm not an admin) this screen shows up:

![image](https://github.com/adarachel/doctors-appointment-frontend/assets/57421823/1351bb4a-f145-4974-ac9b-18d7fa1f3b6a)

Kindly, either make the app print the correct error (You are not an admin, unauthorized) or make those links not appear for non-admin users. 👍 

That way, your UX will be vastly improved. 

- [x] Since your frontend is set to consume the live backend live demo, kindly provide credentials for a test admin user.   You could add it to the PR description, or to the review request.

That way, the "add" and "delete" functionality will be more easily tested.

2023-10-12 10:13 UTC, ankitt26 commented on src/App.js
> +const App = () => (
Thanks, sir, I have implemented these changes 🙂.

2023-10-12 14:29 UTC, Meltrust approved these changes
#### Hi @ankitt26,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)





Cheers and Happy coding!👏👏👏


------

2023-10-12 18:53 UTC, merged